<script>

export default {
    data() {
        return {

        };
    }
}

</script>



<template>
    <div id="goup" class="container my-5 txt_jumbo">
        <div class="row justify-content-center ">
            <div class="col-12 col-lg-8 col-md-8 bg_item rounded-4">
                <h1 class="title">Features & History</h1>
                <p>
                    The area is characterized by intrusion processes
                    of sea water in the surface aquifer and along the final stretch of watercourses,
                    due to subsidence (up to 1.5 mm/year), generated by multiple causes, and del
                    general sea level rise.
                    The presence of a superficial salty aquifer determines salinization phenomena of the soil, sometimes
                    already salty in itself due to its origin from coastal brackish lagoon sediments. <br>
                    This territory, occupied until the 19th century by a system of coastal dunes and brackish lagoons, is
                    today profoundly transformed by the reclamation activities of the 20s and 30s of the 20th century and
                    mainly dedicated to agriculture. <br>
                    Today it includes a large agricultural area and a system of protected semi-natural areas, in particular
                    wetlands, such as the Valle della Canna, the Bardello, the historic pine forest of S. Vitale, which
                    together with the Valle di Comacchio and the Pialasse della Baiona are managed from the Po Delta
                    Regional Park. <br>
                    <hr>
                    The protection regime is due to the presence of one of the largest populations of aquatic birds in
                    Europe linked to the deltaic environments of the Po Delta (Birds Directive 79/409/EEC), to the presence
                    of a large number of habitats of Community interest (Directive Habitat 92/43/EEC) linked mainly to
                    brackish environments typical of lagoon ecosystems, and
                    rare species with a critical conservation status, or threatened with extinction. <br>
                    <hr>
                    It is evident, from the geographical location and from the complex artificial hydrography dictated
                    from the need to keep this area dry, that the challenges related to cultivation
                    are many, and that the availability of fresh water for irrigation, as well as the presence of fresh
                    water bodies, both superficial and deep, are essential to counteract salinization and maintain
                    agriculture.

                </p>
            </div>
        </div>

    </div>
</template>




<style>
.q_qgis {
    color: #ffab1a;
    font-weight: bold;
}

.gis_qgis {
    color: #bddf41;
    font-weight: bold;
}

.py_python {
    color: #fcd648;
    font-weight: bold;
}

.thon_python {
    color: #3da8ff;
    font-weight: bold;
}</style>

